button_to_change_table = '#mode-list'
list_of_elements = '.item.product'
add_to_card_button = 'button[type="submit"][title="Add to Cart"]'
size_button = '#option-label-size-143-item-171'
color = '#option-label-color-93-item-49'
expected_element_added = '.messages[role="alert"]'
expected_element = '.action.add'
after_change = '.product.description.product-item-description'
button_add_to_card = 'button[type=submit][title="Add to Cart"]'
shopping_cart = '.action.showcart'
empty_message = '.subtitle.empty'
